configmod.settings_form:
  path: '/admin/config/configmod/settings'
  defaults:
    _form: '\Drupal\configmod\Form\ConfigurationForm'
    _title: 'ConfigurationForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

configmod.hello:
  path: '/hello'
  defaults:
    _controller: '\Drupal\configmod\Controller\PhpController::hello'
    _title: 'Movie Database'
  requirements:
    _permission: 'access content'
